#!/bin/bash

git add up
git add ./*.py
git add ./*.frag
git add ./*.vert
git add ./*.jpeg
git add ./*.txt
git commit -m "$(date +%s)"
git remote add origin https://github.com/bobbysoon/QtGL_Taxi3D_thing.git
#git remote -v
git push -uf origin master

find . -name "*.pyc" -type f|xargs rm -f

